<?php

class Branch_model extends MY_Model {

	public function __construct() {

		parent::__construct();

		$this->table = 'branch';

	}

	public function check_exists($where = array())
	{
		return parent::check_exists($where); // TODO: Change the autogenerated stub
	}

}

