<?php

class Branch_model extends MY_Model {

	public function __construct() {

		parent::__construct();

		$this->table = 'branch';

	}

	public function check_exists($where = array()) {
		return parent::check_exists($where); // TODO: Change the autogenerated stub
	}

	public function find_branch_name($branch_id) {
		$name = '';
		$input2 = array();
		$input2['where'] = array('id' => $branch_id);
		$branch = $this->load_all($input2);
		if (!empty($branch)) {
			$name = $branch[0]['name'];
		}
		return $name;
	}

}

