<?php

class Class_study_model extends MY_Model {

	public function __construct() {

		parent::__construct();

		$this->table = 'class_study';

	}

	public function check_exists($where = array()) {
		return parent::check_exists($where); // TODO: Change the autogenerated stub
	}

	public function get_class_code($class_id) {
		$input['select'] = 'class_study_id';
		$input['where'] = array('id' => $class_id);
		$a = $this->load_all($input);
		return $a;
	}

}

