<?php

class Level_contact_model extends MY_Model {

	public function __construct() {
		parent::__construct();
		$this->table = 'level_contact';
	}

	public function check_exists($where = array()) {
		return parent::check_exists($where); // TODO: Change the autogenerated stub
	}

	public function get_name_from_level($level_id = '') {
		$input['where'] = array(
			'level_id' => $level_id
		);
		$level_name = $this->load_all($input);
		if (isset($level_name)) {
			return $level_name[0]['level_id'] . ' - ' . $level_name[0]['name'] ;
		} else {
			return $level_id;
		}
	}

}
