<?php

class Level_contact_model extends MY_Model {

	public function __construct() {
		parent::__construct();
		$this->table = 'level_contact';
	}

	public function check_exists($where = array()) {
		return parent::check_exists($where); // TODO: Change the autogenerated stub
	}

}
