<?php

class Time_model extends MY_Model {

	public function __construct() {

		parent::__construct();

		$this->table = 'times';

	}

	public function check_exists($where = array()) {

		return parent::check_exists($where); // TODO: Change the autogenerated stub
	}

	public function get_time($id=0) {
		$name = '';
		$input2 = array();
		$input2['where'] = array('id' => $id);
		$names = $this->load_all($input2);
		if (!empty($names)) {
			$name = $names[0]['times'];
		}
		return $name;
	}

}

